### ISSUE TITLE
Colocar o que tá no README na wiki do GitHub

### ISSUE THREAD

**Issue by CatarinaPBressan** [HardDiskD/TCMCidadeIluminada#3]
@romulolink 

Eu não queria que o README que tá agora fosse colocado na wiki porque ainda tem pessoas que não estão com o ambiente totalmente instalados, e esconder as instruções atrás do link da wiki não ia ajudar.

Assim que todos estiverem com aqueles cartões de instalar o ambiente completos, aí sim vale a pena colocar na wiki e fazer um README decente.

**Comment by romulolink** [comment]
Show de bola @HardDiskD Arthur

**Comment by CatarinaPBressan** [comment]
https://github.com/nicolashery/mac-dev-setup

**Comment by CatarinaPBressan** [comment]
Vou colocar as instruções de instalação aqui. O que for específico do projeto eu vou colocar dfe volta no README

https://github.com/HardDiskD/python-flask-android-setup
